Repository xlayers/xlayers, pull requests merged in 2018-11, with the labels that each got.

#61 fix: sidebar settings menu
  src/app/editor/editor.component.css
  src/app/editor/layer-settings/settings-container/settings-container.component.ts
Labels: PR state: blocked

#70 fix: rethink the preview process
  src/app/core/state/ui.state.ts
  src/app/editor/editor.component.css
  src/app/editor/editor.component.html
  src/app/editor/editor.component.ts
  src/app/editor/layer-settings/settings-container/settings-container.component.ts
  src/app/editor/layer-settings/settings-layer-colors/settings-layer-colors.component.ts
  src/app/editor/layer-settings/settings-preview/settings-preview.component.ts
Labels: review

#76 chore: getting master and develop in an even state
  firebase.json
  scripts/stamp-build.bash
Labels: review

#75 fix: mouse event compatibility
  src/app/editor/viewer/lib/selected-layer.directive.ts
Labels: PR action: discuss

#81 fix: use current domain as an origin to load demo files
  src/app/editor/viewer/lib/sketch.service.ts
Labels: review

#85 feat: add new UI for demo file selection
  angular.json
  src/app/app.module.ts
  src/app/editor/viewer/lib/sketch-select-demo-files.component.ts
  src/app/editor/viewer/lib/sketch.service.ts
  src/environments/environment.hmr.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/styles.css
Labels: review
