Repository xlayers/xlayers, pull requests merged in 2018-09, with the labels that each got.

#18 set header action buttons vertically centered
  src/app/editor/editor.component.css
  src/app/editor/editor.component.html
Labels: PR state: WIP, type: enhancement

#50 refactor: update angular versions to master builds
  package-lock.json
  package.json
Labels: review

#52 chore: merge develop
  Dockerfile
  angular.json
  cloudbuild.yaml
  firebase.json
  local-build.sh
  package-lock.json
  package.json
  scripts/cloudbuild/deploy.sh
  scripts/cloudbuild/kubectl/Dockerfile
  scripts/cloudbuild/kubectl/cloudbuild.yaml
  scripts/cloudbuild/kubectl/kubectl.bash
  scripts/cloudbuild/kubectl/publish.sh
  scripts/cloudbuild/xlayers.template.yaml
  scripts/stamp-build.bash
  scripts/tag-deploy.sh
Labels: review

#51 style(home): avoid horizontal scroll on mobile devices
  src/app/home/landing/landing.component.css
  src/app/home/landing/landing.component.html
  src/styles.css
Labels: PR action: merge
