Repository xlayers/xlayers, pull requests merged in 2019-04, with the labels that each got.

#289 Renaming old sketch lib
  packages/xlayers/src/app/core/sketch.service.mock.ts
  packages/xlayers/src/app/editor/preview/preview.component.ts
  packages/xlayers/src/app/editor/preview/viewer/3d-rotation.directive.ts
  packages/xlayers/src/app/editor/preview/viewer/canvas/canvas.component.spec.ts
  packages/xlayers/src/app/editor/preview/viewer/canvas/canvas.component.ts
  packages/xlayers/src/app/editor/preview/viewer/container/container.component.spec.ts
  packages/xlayers/src/app/editor/preview/viewer/container/container.component.ts
  packages/xlayers/src/app/editor/preview/viewer/layer/layer.component.mock.ts
  packages/xlayers/src/app/editor/preview/viewer/layer/layer.component.spec.ts
  packages/xlayers/src/app/editor/preview/viewer/layer/layer.component.ts
  packages/xlayers/src/app/editor/preview/viewer/layer/selected-layer.directive.ts
  packages/xlayers/src/app/editor/preview/viewer/page/page.component.spec.ts
  packages/xlayers/src/app/editor/preview/viewer/page/page.component.ts
  packages/xlayers/src/app/editor/preview/viewer/stop-event-propagation.directive.ts
  packages/xlayers/src/app/editor/preview/viewer/tooltip.directive.ts
  packages/xlayers/src/app/editor/preview/viewer/viewer.module.ts
  packages/xlayers/src/app/upload/dropzone/dropzone.component.css
  packages/xlayers/src/app/upload/dropzone/dropzone.component.html
  packages/xlayers/src/app/upload/dropzone/dropzone.component.mock.ts
  packages/xlayers/src/app/upload/dropzone/dropzone.component.spec.ts
  packages/xlayers/src/app/upload/dropzone/dropzone.component.ts
  packages/xlayers/src/app/upload/select-demo-files/select-demo-files.component.css
  packages/xlayers/src/app/upload/select-demo-files/select-demo-files.component.html
  packages/xlayers/src/app/upload/select-demo-files/select-demo-files.component.spec.ts
  packages/xlayers/src/app/upload/select-demo-files/select-demo-files.component.ts
  packages/xlayers/src/app/upload/upload.component.html
  packages/xlayers/src/app/upload/upload.module.ts
  tests/integration/sketch-parsing.spec.ts
Labels: pr: cleanup, review, status: blocked

#290 refactor: move home outside app scope
  packages/xlayers/src/app/app.module.ts
  packages/xlayers/src/home/home.module.ts
  packages/xlayers/src/home/interactive-bg/interactive-bg.component.css
  packages/xlayers/src/home/interactive-bg/interactive-bg.component.html
  packages/xlayers/src/home/interactive-bg/interactive-bg.component.spec.ts
  packages/xlayers/src/home/interactive-bg/interactive-bg.component.ts
  packages/xlayers/src/home/landing/landing.component.css
  packages/xlayers/src/home/landing/landing.component.html
  packages/xlayers/src/home/landing/landing.component.spec.ts
  packages/xlayers/src/home/landing/landing.component.ts
Labels: review

#297 feat: new framework selection
  src/app/editor/code/editor-container/editor-container.component.css
  src/app/editor/code/editor-container/editor-container.component.html
Labels: review

#293 test: landing e2e
  package-lock.json
  package.json
  tests/e2e/fixtures/md-components.sketch
  tests/e2e/specs/editor.spec.js
  tests/e2e/support/commands.js
Labels: pr: cleanup, review

#294 test: Interaction e2e
  tests/e2e/fixtures/test-sample.sketch
  tests/e2e/specs/interactions.spec.js
Labels: review
