Repository xlayers/xlayers, pull requests merged in 2019-01, with the labels that each got.

#146 feature(editor): Download image preview
  src/app/editor/layer-settings/settings-preview/settings-preview.component.ts
Labels: State: WIP

#132 bug(codeeditor): Fix too many scrollbars
  package-lock.json
  src/app/editor/code-editor/code-editor.module.ts
  src/app/editor/code-editor/editor-container/editor-container.component.ts
Labels: PR action: discuss

#143 fix wc's export
  src/app/editor/code-editor/editor-container/codegen/wc/wc.service.ts
  src/app/editor/code-editor/editor-container/codegen/wc/wc.template.ts
  src/app/editor/exports/stackblitz/stackblitz.service.ts
  src/app/editor/exports/stackblitz/stackblitz.wc.service.ts
Labels: State: WIP

#157 chore: improved legacy sketch parser
  src/app/editor/viewer/lib/parsers/sketch-style-parser.service.spec.ts
  src/app/editor/viewer/lib/parsers/sketch-style-parser.service.ts
  src/app/editor/viewer/lib/sketch-layer.component.ts
  src/app/editor/viewer/lib/sketch.service.ts
Labels: review

#159 fix: unzip crash
  src/app/editor/viewer/lib/sketch-container.component.ts
  src/app/editor/viewer/lib/sketch.service.spec.ts
  src/app/editor/viewer/lib/sketch.service.ts
Labels: PR action: cleanup, review

#164 fix(editor): Replace Monaco editor with a simple code bloc
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/editor/code-editor/code-editor.module.ts
  src/app/editor/code-editor/editor-container/codegen/codegen.service.ts
  src/app/editor/code-editor/editor-container/editor-container.component.ts
  src/styles.css
Labels: PR action: cleanup, State: WIP

#167 Add independent export button per CodeGen
  src/app/core/state/page.state.ts
  src/app/core/state/ui.state.ts
  src/app/editor/code-editor/editor-container/codegen/angular/angular.service.ts
  src/app/editor/code-editor/editor-container/codegen/codegen.service.ts
  src/app/editor/code-editor/editor-container/codegen/react/react.service.ts
  src/app/editor/code-editor/editor-container/codegen/vue/vue.service.ts
  src/app/editor/code-editor/editor-container/codegen/wc/wc.service.ts
  src/app/editor/code-editor/editor-container/editor-container.component.spec.ts
  src/app/editor/code-editor/editor-container/editor-container.component.ts
  src/app/editor/editor.component.html
  src/app/editor/editor.component.ts
  src/app/editor/exports/stackblitz/stackblitz.service.ts
Labels: PR action: merge, review
