Repository xlayers/xlayers, pull requests merged in 2019-03, with the labels that each got.

#220 chore(build): add support for automatic release
  .release-it.json
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/clean-changelog.js
Labels: review

#221 core: add workspace recommendations
  .vscode/extensions.json
Labels: review

#227 core: changed language to css for correct comment
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/angular/angular.service.ts
Labels: review

#228 chore: verify commit message before commiting
  .commitlintrc.json
  package-lock.json
  package.json
Labels: review

#233 docs: remove old github parser issue template
  .github/ISSUE_TEMPLATE/parser--add-xxxxx-support.md
Labels: review

#232 docs: remove old github ui tool issue template
  .github/ISSUE_TEMPLATE/ui-designer-tool--add-support-for-xxxxx.md
Labels: review

#231 docs: remove old github codgen issue template
  .github/ISSUE_TEMPLATE/codegen--add-xxxxx-support.md
Labels: review

#235 docs: remove old github parser ui issue template
  .github/ISSUE_TEMPLATE/parser--add---ui-tool---support.md
Labels: review

#236 docs: remove old github file format issue template
  .github/ISSUE_TEMPLATE/parser--add---file-format---support.md
Labels: review

#239 fix: update the github new issue template
  packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts
Labels: review

#246 feat: add badge for the current environnement
  packages/xlayers/src/app/app.module.ts
  packages/xlayers/src/app/core/core.module.ts
  packages/xlayers/src/app/core/window.service.ts
  packages/xlayers/src/app/editor/editor.component.html
  packages/xlayers/src/app/editor/editor.component.spec.ts
  packages/xlayers/src/app/editor/editor.component.ts
  packages/xlayers/src/app/editor/editor.module.ts
  packages/xlayers/src/app/editor/preview-badge.service.ts
Labels: review

#251 docs: add PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review

#250 fix: preview border
  packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.ts
Labels: review, status: WIP

#254 fix: update SEO meta tags
  packages/xlayers/src/index.html
Labels: review

#222 core(codegen) the css optimization
  packages/sketchapp-parser/src/lib/style-optimizer.service.spec.ts
  packages/sketchapp-parser/src/lib/style-optimizer.service.ts
  packages/sketchapp-parser/src/public_api.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/angular/angular.service.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/shared-codegen.service.ts
Labels: priority: High, review

#241 feat: add images assets support
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/angular/angular.service.spec.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/codegen.service.spec.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/lit-element/lit-element.service.spec.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/react/react.service.spec.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/shared-codegen.service.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/stencil/stencil.service.spec.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/vue/vue.service.spec.ts
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/wc/wc.service.spec.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch-container.component.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.spec.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch-page.component.spec.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch-page.component.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch.service.spec.ts
  packages/xlayers/src/app/editor/viewer/lib/sketch.service.ts
  tests/integration/sketch-parsing.spec.ts
Labels: priority: High, review

#255 fix(editor): zooming options will be highlighted
  packages/xlayers/src/app/editor/editor.component.html
  packages/xlayers/src/app/editor/editor.component.spec.ts
  packages/xlayers/src/app/editor/editor.component.ts
Labels: review

#225 fix(editor): code editor page down/up key scroll issue fixed
  package-lock.json
  packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts
Labels: priority: High, review, status: WIP

#259 feat: improve the editor footer
  packages/xlayers/src/app/editor/editor.component.css
  packages/xlayers/src/app/editor/editor.component.html
  packages/xlayers/src/assets/github-circle.png
  packages/xlayers/src/assets/twitter.png
Labels: review

#257 refactor: update app title for more consistency
  packages/xlayers/src/app/editor/editor.component.css
  packages/xlayers/src/app/editor/editor.component.html
Labels: review

#258 chore: add lint-staged
  package-lock.json
  package.json
Labels: review

#263 test: implemented for the badge service
  packages/xlayers/src/app/editor/preview-badge.service.spec.ts
Labels: review

#264 test: add some extra test around stackblitz services
  packages/xlayers/src/app/editor/code-editor/editor-container/codegen/codegen.service.spec.ts
  packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.angular.service.spec.ts
  packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.lit-element.service.spec.ts
  packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.react.service.spec.ts
Labels: review

#262 refactor(core): ngxs patch operators to simplify nested state operations
  packages/xlayers/src/app/core/state/ui.state.ts
Labels: review

#260 refactor: enable BrowserAnimationsModule
  package.json
  packages/xlayers/src/app/app.module.ts
  packages/xlayers/src/app/editor/editor.component.css
  packages/xlayers/src/app/editor/editor.component.html
Labels: review

#265 test: all framework services are tested
  packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.stencil.service.spec.ts
  packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.vue.service.spec.ts
  packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.wc.service.spec.ts
Labels: review

#268 fix: small fixes after restructure
  packages/xlayers/src/app/editor/code/editor-container/editor-container.component.css
  packages/xlayers/src/app/editor/editor.component.html
  packages/xlayers/src/app/editor/editor.component.ts
  packages/xlayers/src/app/editor/preview/preview.component.ts
  packages/xlayers/src/app/upload/upload.component.ts
Labels: review

#269 fix: twitter card
  packages/xlayers/src/index.html
Labels: review

#276 chore: update CI script to improve Cypress install
  package.json
Labels: review

#284 Enrich parser test
  package-lock.json
  package.json
  packages/sketchapp-parser/src/lib/sketch-style-parser.service.spec.ts
  packages/sketchapp-parser/src/lib/sketch-style-parser.service.ts
Labels: review

#288 feat: make the 3d design rotate
  packages/xlayers/src/app/editor/preview/viewer/3d-rotation.directive.ts
  packages/xlayers/src/app/editor/preview/viewer/sketch-canvas/sketch-canvas.component.ts
  packages/xlayers/src/app/editor/preview/viewer/sketch-container/sketch-container.component.ts
  packages/xlayers/src/app/editor/preview/viewer/sketch-layer/sketch-layer.component.ts
  packages/xlayers/src/app/editor/preview/viewer/sketch-page/sketch-page.component.ts
  packages/xlayers/src/app/editor/preview/viewer/viewer.module.ts
Labels: review

#285 Add cypress tests
  .circleci/config.yml
  .gitignore
  cypress.json
  jest.config.js
  package-lock.json
  package.json
  tests/e2e/fixtures/.keep
  tests/e2e/plugins/index.js
  tests/e2e/specs/home.spec.js
  tests/e2e/support/commands.js
Labels: review
