Repository xlayers/xlayers, pull requests merged in 2019-02, with the labels that each got.

#160 WIP Feature/include stenciljs
  package-lock.json
  src/app/app.component.ts
  src/app/editor/code-editor/editor-container/codegen/codegen.module.ts
  src/app/editor/code-editor/editor-container/codegen/codegen.service.ts
  src/app/editor/code-editor/editor-container/codegen/stencil/stencil.service.spec.ts
  src/app/editor/code-editor/editor-container/codegen/stencil/stencil.service.ts
  src/app/editor/code-editor/editor-container/codegen/stencil/stencil.template.ts
  src/app/editor/code-editor/editor-container/editor-container.component.ts
  src/app/editor/exports/stackblitz/stackblitz.service.ts
  src/app/editor/exports/stackblitz/stackblitz.stencil.service.ts
  src/assets/codegen/stencil.svg
Labels: PR action: merge

#177 feat: add support for pdf previews
  angular.json
  package-lock.json
  package.json
  src/app/core/state/ui.state.ts
  src/app/editor/editor.component.ts
  src/app/editor/editor.module.ts
  src/app/editor/tree-view/tree-view.component.ts
  src/app/editor/viewer/lib/sketch-canvas.component.ts
  src/app/editor/viewer/lib/sketch.service.ts
Labels: review

#182 feat: upgrade to angular 8.0.0-beta.3
  package-lock.json
  package.json
  packages/sketchapp-parser/package.json
Labels: review

#175 Add parser integration test
  test/e2e/plugins/index.js
  test/e2e/specs/.keep
  test/e2e/support/commands.js
  test/e2e/support/index.js
  test/integration/sketch-parsing.spec.ts
  test/snapshots/49/md-components-buttons-fabs-light.sketch.json
  test/snapshots/49/md-components-buttons-lights.sketch.json
  test/snapshots/49/md-components-cards-homes.sketch.json
  test/snapshots/49/md-components-cards-pooch.sketch.json
  test/snapshots/49/md-components-cards-safari.sketch.json
  test/snapshots/49/md-components-cards-welcome-back.sketch.json
  test/snapshots/49/md-components-chips-open-chip.sketch.json
  test/snapshots/49/md-components-date-picker.sketch.json
  test/snapshots/49/md-components-tabs-status-bar.sketch.json
  test/snapshots/50/md-components-buttons-fabs-light.sketch.json
  test/snapshots/50/md-components-buttons-lights.sketch.json
  test/snapshots/50/md-components-cards-homes.sketch.json
  test/snapshots/50/md-components-cards-pooch.sketch.json
  test/snapshots/50/md-components-cards-safari.sketch.json
  test/snapshots/50/md-components-cards-welcome-back.sketch.json
  test/snapshots/50/md-components-chips-open-chip.sketch.json
  test/snapshots/50/md-components-date-picker.sketch.json
  test/snapshots/50/md-components-notifications-heads-up.sketch.json
  test/snapshots/50/md-components-tabs-status-bar.sketch.json
  test/snapshots/51/md-components-buttons-fabs-light.sketch.json
  test/snapshots/51/md-components-buttons-lights.sketch.json
  test/snapshots/51/md-components-cards-homes.sketch.json
  test/snapshots/51/md-components-cards-pooch.sketch.json
  test/snapshots/51/md-components-cards-safari.sketch.json
  test/snapshots/51/md-components-cards-welcome-back.sketch.json
  test/snapshots/51/md-components-chips-open-chip.sketch.json
  test/snapshots/51/md-components-date-picker.sketch.json
  test/snapshots/51/md-components-notifications-heads-up.sketch.json
  test/snapshots/51/md-components-tabs-status-bar.sketch.json
  test/snapshots/52/md-components-buttons-fabs-light.sketch.json
  test/snapshots/52/md-components-buttons-lights.sketch.json
  test/snapshots/52/md-components-cards-homes.sketch.json
  test/snapshots/52/md-components-cards-pooch.sketch.json
  test/snapshots/52/md-components-cards-safari.sketch.json
  test/snapshots/52/md-components-cards-welcome-back.sketch.json
  test/snapshots/52/md-components-chips-open-chip.sketch.json
  test/snapshots/52/md-components-date-picker.sketch.json
  test/snapshots/52/md-components-notifications-heads-up.sketch.json
  test/snapshots/52/md-components-tabs-status-bar.sketch.json
Labels: State: WIP, review

#174 feat(changelog) added changelog
  package-lock.json
  package.json
Labels: State: WIP

#194 Feat/GitHub action
  .circleci/config.yml
  .github/main.workflow
  package-lock.json
  package.json
Labels: review

#198 refactor(app): Remove bugsnag client
  package-lock.json
  package.json
  packages/xlayers/src/app/editor/error-report.service.ts
Labels: review

#199 Add zoom reset icon
  packages/xlayers/src/app/core/state/ui.state.ts
  packages/xlayers/src/app/editor/editor.component.html
  packages/xlayers/src/app/editor/editor.component.ts
Labels: review

#205 fix(editor): Removed PDF preview for now
  angular.json
  package-lock.json
  package.json
  packages/xlayers/src/app/editor/viewer/lib/sketch.service.ts
Labels: review

#210 fix: jest snapshot update
  package.json
Labels: review

#209 Fix: Independent drag
  packages/xlayers/src/app/editor/viewer/lib/sketch-canvas.component.ts
Labels: review

#211 chore(release): 1.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: PR action: discuss, review

#216 fix: config ci
  .circleci/config.yml
Labels: review

#218 Angular libs from dist to src
  tsconfig.json
Labels: review

#219 chore(ci): have separate jobs
  .circleci/config.yml
Labels: review
